Repository ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e4-aplicdistrib-t5-pmv-ads-2023-2-e4-g2-taskit, pull requests merged in 2023-10, with the labels that each got.

#47 feat: add session and api auth
  src/web/package.json
  src/web/src/app/api/v1/auth/auth.service.ts
  src/web/src/app/api/v1/auth/login/route.ts
  src/web/src/app/api/v1/users/[id]/route.ts
  src/web/src/app/api/v1/users/route.ts
  src/web/src/app/api/v1/users/user.service.ts
  src/web/src/shared/api/useServerAuth.ts
  src/web/yarn.lock
Labels: enhancement, code

#49 feat(34): conclude user and auth route
  src/web/openapi.yml
  src/web/src/app/api/v1/auth/auth.service.ts
  src/web/src/app/api/v1/auth/login/route.ts
  src/web/src/app/api/v1/auth/logout/route.ts
  src/web/src/app/api/v1/auth/routedoc.ts
  src/web/src/app/api/v1/route.ts
  src/web/src/app/api/v1/tasks/routedoc.ts
  src/web/src/app/api/v1/users/[id]/route.ts
  src/web/src/app/api/v1/users/route.ts
  src/web/src/app/api/v1/users/routedoc.ts
  src/web/src/shared/interfaces/apidocs.interface.ts
Labels: documentation, enhancement, code

#51 Update 05-Arquitetura da Solução- Tecnologias utilizadas
  docs/05-Arquitetura da Solução.md
Labels: documentation

#52 Update 05-Arquitetura da Solução.md
  docs/05-Arquitetura da Solução.md
Labels: documentation

#53 feat: add task route
  src/web/package.json
  src/web/src/app/api/v1/auth/login/route.ts
  src/web/src/app/api/v1/tasks/[id]/route.ts
  src/web/src/app/api/v1/tasks/[id]/subtasks/[subtask_id]/route.ts
  src/web/src/app/api/v1/tasks/[id]/subtasks/route.ts
  src/web/src/app/api/v1/tasks/route.ts
  src/web/src/app/api/v1/tasks/routedoc.ts
  src/web/src/app/api/v1/tasks/task.service.ts
  src/web/src/app/api/v1/users/[id]/route.ts
  src/web/src/app/login/page.tsx
  src/web/src/app/users/[id]/page.tsx
Labels: documentation, enhancement, code

#66 Update 04-Projeto de Interface.md wireframes
  docs/04-Projeto de Interface.md
Labels: documentation
